name: Hola Mundo PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - staging

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: hello World
    steps:
      - name: Run Hello World
        run: |
          echo "Hola Mundo"
